### ISSUE TITLE
AMReX 19.06 no longer requires blitz++

### ISSUE THREAD

**Issue by asalmgren** [otbrown/LAMBReX#11]
Hi -- I saw your comment at https://github.com/otbrown/LAMBReX/tree/AMR about blitz++ being required -- just an FYI that as of version 19.06, AMReX no longer has any dependence on blitz.

**Comment by otbrown** [comment]
Thanks for the heads up @asalmgren! We're currently developing with 19.05, but I'll make sure to update the README when I move to 19.07 (or possibly 19.08, by the time I get around to it...) .
